import Head from 'next/head';
import React from 'react'
import LayoutAdmin from '../components/layout/admin'

const AdminPage = () => {
  return (
    <div>
        <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
      
      AdminPage</div>
  )
}

AdminPage.Layout = LayoutAdmin;

export default AdminPage